# Generated by Django 6.0.2 on 2026-02-20 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_registerusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registerUsers',
        ),
    ]
